name: CloudShield DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    # SonarQube Scan
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # Docker Login
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudshield:latest .

    # Trivy Scan
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/cloudshield:latest
        format: table
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    # Push Image
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cloudshield:latest

    # Kubernetes Deploy
    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/cloudshield.yaml
